### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by zhourui123** [Chisel-Team/ConnectedTexturesMod#103]
This problem happens randomly
https://gist.github.com/zhourui123/619a4679b2226c6bd4b50e4fd5e9ddb8
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CTM (ctm)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.client.Minecraft.field_110452_an from class team.chisel.ctm.CTM
	at team.chisel.ctm.CTM.preInit(CTM.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

```

There's a similar problem here, but the solution doesn't seem to apply to me
#47

**Comment by zhourui123** [comment]
I looked carefully, not sure if 'FileNotFoundException' caused the `_at` file was not added correctly.
Can you take a look at it for me?
thank you !

https://gist.github.com/zhourui123/1f4ac091ae2fda02d0c70103d55b8614

**Comment by tterrag1098** [comment]
Your log is partially non-english, so it's a bit hard to read. You also have strange names for all your mod jars, and tons of invalid jar files in the mods directory.

Additionally I see two netease coremods which I have no idea what they are doing.

I would recommend you download chisel/ctm from official sources, and not rename files.

**Comment by zhourui123** [comment]
The odd thing is that sometimes it throws FileNotFoundException, and sometimes it's normal
1.(系统找不到指定的路径) equals (The system cannot find the file specified)
2.netease coremod  i guess is mainly to filter chat, monitor online number of player.
3.Rename is a mechanism in Netease that prevents players from tampering with mods.
4.It can't be reproduced in my local environment, it only appears in netease production, where I can't debug. I can't find any similar problem in Google. Can you give me some advice?Some people say it might be a change in `current working dir` , but I don't think so.
```
java.io.FileNotFoundException: .\mods\4632759211054187818@2@8.jar (系统找不到指定的路径。)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_60]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:353) [forge-1.12.2-14.23.4.2705.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:252) [forge-1.12.2-14.23.4.2705.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:105) [forge-1.12.2-14.23.4.2705.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79) [forge-1.12.2-14.23.4.2705.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) [forge-1.12.2-14.23.4.2705.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:139) [forge-1.12.2-14.23.4.2705.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:121) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:23) [launchwrapper-1.12.jar:?]
```

**Comment by tterrag1098** [comment]
If it works locally but not with netease mods then the blame seems obvious. Unless you can reproduce with only chisel/ctm I'm not sure what I can do. Your errors are coming from forge, CTM is just a casualty of the problems there.

**Comment by zhourui123** [comment]
First, thank you for your kindness.

They seem reluctant to admit that they are the problem, and the progress of their work order is slow. I want to try to solve the problem by myself. 

I have no way out, I assume it's a current working directory problem, I want to write a core mod that change  `mcDir` in `FMLTweaker.class` or `CoreModManager.class` from relative path `.` to absolute path. I've never tried to write a core mod and I don't know if it can be asm to such a core class.

(I know that MC home can be passed in through the launch flags, but the installation path is different for each player)

**Comment by tterrag1098** [comment]
Could work, I really have no idea. Best of luck though.
