### ISSUE TITLE
A crash from 1.12

### ISSUE THREAD

**Issue by Protodragon01** [Chisel-Team/ConnectedTexturesMod#147]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 12/30/20 5:29 PM
Description: Initializing game

net.minecraft.client.renderer.StitcherException: Unable to fit: twilightforest:items/ironwood_boots - size: 16x16 - Maybe try a lowerresolution resourcepack?
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:70)
	at net.minecraft.client.renderer.texture.TextureMap.finishLoading(TextureMap.java:216)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:112)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:70)
	at net.minecraft.client.renderer.texture.TextureMap.finishLoading(TextureMap.java:216)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:112)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 236342632 bytes (225 MB) / 1811939328 bytes (1728 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version           | Source                                        | Signature |
	|:----- |:----------------- |:----------------- |:--------------------------------------------- |:--------- |
	| LCH   | minecraft         | 1.12.2            | minecraft.jar                                 | None      |
	| LCH   | mcp               | 9.42              | minecraft.jar                                 | None      |
	| LCH   | FML               | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                 | None      |
	| LCH   | forge             | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                 | None      |
	| LCH   | foamfixcore       | 7.7.4             | minecraft.jar                                 | None      |
	| LCH   | baubles           | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None      |
	| LCH   | ebwizardry        | 4.3.1             | ElectroblobsWizardry-4.3.1-MC1.12.2.jar       | None      |
	| LCH   | ancientspellcraft | 1.1.0             | AncientSpellcraft-1.1.0.jar                   | None      |
	| LCH   | bibliocraft       | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar             | None      |
	| LCH   | ctm               | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                     | None      |
	| LCH   | rcraft            | 2.1.7             | dotHack+Weapons-2.1.7.jar                     | None      |
	| LCH   | extra_spells      | 1.2.0             | ExtraSpells-1.12.2-1.2.0.jar                  | None      |
	| LCH   | foamfix           | 0.10.10-1.12.2    | foamfix-0.10.10-1.12.2.jar                    | None      |
	| LCH   | grimoireofgaia    | 1.6.9.3           | GrimoireOfGaia3-1.12.2-1.6.9.3.jar            | None      |
	| LCH   | patchouli         | 1.0-20            | Patchouli-1.0-20.jar                          | None      |
	| LCH   | twilightforest    | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar | None      |
	| LCH   | tfspellpack       | 1.1.0             | TFSpellPack-1.1.0-MC1.12.2.jar                | None      |
	| LCH   | zettaimagic       | 1.1.0             | ZettaiMagic+1.1.0.jar                         | None      |

	Loaded coremods (and transformers): 
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 25.20.100.6444' Renderer: 'Intel(R) UHD Graphics 620'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 25.20.100.6444, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft 256x MC112
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

**Comment by Ludi87** [comment]
Did you try without a 256x resource pack on an integrated gpu?

**Comment by tterrag1098** [comment]
You're out of texture space, not a CTM bug.
