### ISSUE TITLE
[1.12.2] Single player crash after breaking sandstone block

### ISSUE THREAD

**Issue by joselitosn** [Chisel-Team/ConnectedTexturesMod#37]
After breaking a block of normal sandstone near a Thermal Expansion machine the game crashed, after that i can't open the saved world. It crashes with the same message.

https://pastebin.com/6rvqjzFe

```
java.lang.NullPointerException: Tesselating block model
    at codechicken.lib.model.bakery.ModelBakery.getCachedModel(ModelBakery.java:235)
    at codechicken.lib.model.bakery.CCBakeryModel.func_188616_a(CCBakeryModel.java:40)
    at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1364)
    at ConnectedTextures.isNeighbour(ConnectedTextures.java:1323)
    at ConnectedTextures.isNeighbour(ConnectedTextures.java:1303)
    at ConnectedTextures.getConnectedTextureTop(ConnectedTextures.java:1695)
    at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:545)
    at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:370)
    at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:299)
    at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:113)
    at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:89)
    at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:60)
    at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:110)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
    at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:76)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:55)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
    at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:296)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
    at java.lang.Thread.run(Thread.java:745)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Client thread
Stacktrace:
    at codechicken.lib.model.bakery.ModelBakery.getCachedModel(ModelBakery.java:235)
    at codechicken.lib.model.bakery.CCBakeryModel.func_188616_a(CCBakeryModel.java:40)
    at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1364)
    at ConnectedTextures.isNeighbour(ConnectedTextures.java:1323)
    at ConnectedTextures.isNeighbour(ConnectedTextures.java:1303)
    at ConnectedTextures.getConnectedTextureTop(ConnectedTextures.java:1695)
    at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:545)
    at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:370)
    at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:299)
    at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:113)
    at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:89)
    at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:60)
    at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:110)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
```

**Comment by tterrag1098** [comment]
Yeah that's Optifine CTM, not us.

**Comment by joselitosn** [comment]
Thank you, removing it allowed me to open the game again. I wish the logs were more clear about it, but i guess it should be expected Optifine cause all sorts of problems.

Again, thank you for the quick response. Happy Holidays.
