### ISSUE TITLE
CTM crash with techincklauncher

### ISSUE THREAD

**Issue by LordsOfWolfs** [Chisel-Team/ConnectedTexturesMod#87]
Hello I am trying to run ctm for my custom modpack, but I keep getting these crashes.
Could you help me please?
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 12/10/18 2:46 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CTM (ctm)
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 116
Exception Details:
  Location:
    net/minecraftforge/client/model/ModelLoader$VanillaModelWrapper.getTextures()Ljava/util/Collection; @116: invokestatic
  Reason:
    Type 'net/minecraftforge/client/model/IModel' (current frame, locals[1]) is not assignable to 'net/minecraft/util/ResourceLocation' (stack map, locals[1])
  Current Frame:
    bci: @14
    flags: { }
    locals: { 'net/minecraftforge/client/model/ModelLoader$VanillaModelWrapper', 'net/minecraftforge/client/model/IModel' }
    stack: { 'net/minecraftforge/client/model/IModel' }
  Stackmap Frame:
    bci: @116
    flags: { }
    locals: { 'net/minecraftforge/client/model/ModelLoader$VanillaModelWrapper', 'net/minecraft/util/ResourceLocation' }
    stack: { }
  Bytecode:
    0x0000000: 2ab4 0044 b600 9b4c 2bb8 00b5 4c2b c600
    0x0000010: 662a b400 44b4 00b8 c700 5c2b b600 9e12
    0x0000020: bab6 00bb 9900 102a b400 44b8 00bf b500
    0x0000030: b8a7 0043 2ab4 0044 2bbb 0080 59b7 0081
    0x0000040: 12c1 b600 872b b600 8a12 c3b6 0087 2ab4
    0x0000050: 0044 b600 8a12 c5b6 0087 b600 8db8 0093
    0x0000060: b900 c901 002a ba00 db00 00b6 00e1 c000
    0x0000070: 54b5 00b8 b800 e54d 2ab4 003d 2ab4 0044
    0x0000080: b800 e999 004a b200 efb9 00f2 0100 4e2d
    0x0000090: b900 6501 0099 0038 2db9 0069 0100 c000
    0x00000a0: a23a 042a b400 4419 04b6 00f6 3a05 bb00
    0x00000b0: 6b59 1905 b700 f93a 0619 0519 04b6 00bb
    0x00000c0: 9a00 0a2c 1906 b600 fc57 a7ff c52a b400
    0x00000d0: 44b4 0100 b901 0301 00b9 005d 0100 4e2d
    0x00000e0: b900 6501 0099 002a 2db9 0069 0100 c000
    0x00000f0: a23a 0419 0413 0105 b600 a69a 0011 2cbb
    0x0000100: 006b 5919 04b7 00f9 b600 fc57 a7ff d32c
    0x0000110: b601 09b0                              
  Stackmap Table:
    append_frame(@52,Object[#107])
    same_frame(@116)
    append_frame(@143,Object[#14],Object[#97])
    same_frame(@202)
    chop_frame(@205,1)
    append_frame(@223,Object[#97])
    same_frame(@268)
    chop_frame(@271,1)

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at team.chisel.ctm.client.util.TextureMetadataHandler.<clinit>(TextureMetadataHandler.java:96)
	at team.chisel.ctm.CTM.preInit(CTM.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 15748621304 bytes (15019 MB) / 16106127360 bytes (15360 MB) up to 16106127360 bytes (15360 MB)
	JVM Flags: 5 total; -Xms15360m -Xmx15360m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID               | Version           | Source                            | Signature                                |
	|:----- |:---------------- |:----------------- |:--------------------------------- |:---------------------------------------- |
	| LCH   | minecraft        | 1.12.2            | minecraft.jar                     | None                                     |
	| LCH   | mcp              | 9.42              | minecraft.jar                     | None                                     |
	| LCH   | FML              | 8.0.99.99         | modpack.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge            | 14.23.5.2796      | modpack.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | baubles          | 1.5.2             | Baubles-1.12-1.5.2.jar            | None                                     |
	| LCE   | ctm              | MC1.12-0.2.3.9    | CTM-MC1.12-0.2.3.9.jar            | None                                     |
	| LC    | chisel           | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar      | None                                     |
	| LC    | jei              | 4.13.1.225        | jei_1.12.2-4.13.1.225.jar         | None                                     |
	| LC    | mantle           | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar          | None                                     |
	| LC    | tconstruct       | 1.12.2-2.11.0.106 | TConstruct-1.12.2-2.11.0.106.jar  | None                                     |
	| LC    | extrautils2      | 1.0               | extrautils2-1.12-1.9.8.jar        | None                                     |
	| LC    | howlingmoon      | 0.9               | howlingmoon-1.12.2-0.9.jar        | None                                     |
	| LC    | moreplayermodels | 1.12.2            | More-Player-Models-Mod-1.12.2.jar | None                                     |
	| LC    | vampirism        | 1.4.5             | Vampirism-1.12.2-1.4.5.jar        | None                                     |
	| LC    | teamlapen-lib    | 1.4.5             | Vampirism-1.12.2-1.4.5.jar        | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

**Comment by LordsOfWolfs** [comment]
ty
